prometheus:
  url: http://prometheus-server.monitoring.svc
  port: 80

rules:
  default: false
  custom:
    - seriesQuery: 'http_server_requests_seconds_count'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "http_server_requests_seconds_count"
        as: "http_requests_per_second"
      metricsQuery: |
        sum(rate(http_server_requests_seconds_count[1m])) by (<<.GroupBy>>)
