apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: spring-boot-postgres-demo
data:
  POSTGRES_DB: "testdb"
  POSTGRES_USER: "postgres"
  POSTGRES_DB_URL: "jdbc:postgresql://postgres-release-postgresql:5432/testdb"