prometheus:
  url: http://prometheus-monitoring-kube-prometheus-prometheus.monitoring.svc
  port: 9090

service:
  type: ClusterIP
  port: 443
  targetPort: 6443

rules:
  default: false
  custom:
    - seriesQuery: 'http_server_requests_seconds_count'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "http_server_requests_seconds_count"
        as: "http_requests_per_second"
      metricsQuery: |
        sum(rate(http_server_requests_seconds_count[1m])) by (<<.GroupBy>>)
